import { Book } from './book';

export const BOOKS: Book[] = [
  { id: 1, name: 'Casas Muertas', author:'Miguel Otero Silva', quote:'Una casa muerta, entre mil casas muertas, mascullando el mensaje desesperado de una época desaparecida', description:'Casas Muertas es la segunda novela del escritor venezolano Miguel Otero Silva, fue publicada por Editorial Losada, en el año 1955'},
  { id: 2, name: 'Las lanzas coloradas', author:'Arturo Uslar Pietri', quote:'¡Noche oscura! Venía chorreando el agua, chorreando, chorreando, como si ordeñaran el cielo', description:'Las lanzas coloradas es una novela del escritor venezolano Arturo Uslar Pietri, escrita en París en 1929/1930 y publicada en 1931 en Madrid (Editorial Zeus), en la cual relata un episodio de la guerra de independencia de Venezuela, cuando la región del llano fue asolada por el general realista Boves'},
  { id: 3, name: 'El amor en los tiempos del colera', author:'Gabriel Garcia Marquez', quote:'Lo único que me duele de morir, es que no sea de amor', description:'El amor en los tiempos del cólera es una novela del escritor colombiano Gabriel García Márquez, publicada en 1985.'},
  { id: 4, name: 'Rayuela', author:'Julio Cortazar', quote:'Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos', description:'Escrita en París y publicada por primera vez el 28 de junio de 1963'},
  { id: 5, name: 'La casa de los espiritus', author:'Isabel Allende', quote:'Igual que en el momento de venir al mundo, al morir tenemos miedo de lo desconocido', description:'La casa de los espíritus es la primera novela de la escritora chilena Isabel Allende, publicada en Buenos Aires por Editorial Sudamericana en 1982'},
  { id: 6, name: 'Doña Bárbara', author:'Romulo Gallegos', quote:'Algún día será verdad. El progreso penetrará en la llanura y la barbarie retrocederá vencida', description:'Doña Bárbara es una novela escrita por el venezolano Rómulo Gallegos y publicada por Editorial Araluce, el 15 de febrero de 1929'},
  { id: 7, name: 'Veinte poemas de amor y una cancion desesperada', author:'Pablo Neruda', quote:'Es tan corto el amor y tan largo el olvido', description:'Veinte poemas de amor y una canción desesperada es una de las más célebres obras del poeta chileno Pablo Neruda (1904-1973). Publicado en 1924, el poemario lanzó a su autor a la fama con apenas 19 años de edad, y es una de las obras literarias de mayor renombre del siglo XX en la lengua española'},
  { id: 8, name: 'El tunel', author:'Ernesto Sabato', quote:'Que el mundo es horrible, es una verdad que no necesita demostración', description:'El túnel es una novela corta argentina escrita por Ernesto Sábato en 1948. Juan Pablo Castel, personaje principal y narrador, cuenta desde la cárcel los motivos que lo llevaron a asesinar a María Iribarne, su amante'},
  { id: 9, name: 'La ciudad y los perros', author:'Mario Vargas Llosa', quote:'El amor es lo peor que hay. Uno anda hecho un idiota y ya no se preocupa de sí mismo', description:'La ciudad y los perros es la primera novela del escritor peruano Mario Vargas Llosa. Ganador con el Premio Biblioteca Breve en 1962, fue publicada en octubre de 1963 y ganó el Premio de la Crítica Española. '},
];
